### ISSUE TITLE
Cannot find module './SimpleSchema' error

### ISSUE THREAD

**Issue by retani** [aldeed/meteor-collection2-core#36] opened 2017-07-30 07:55 UTC
Hi there,

I have installed collection2-core on my meteor project as suggested:

```
$ meteor add aldeed:collection2-core
$ meteor npm install --save simpl-schema
```

Right at `meteor run` I get a strage error:

```
W20170730-09:36:24.740(2)? (STDERR) /Users/USER/.meteor/packages/meteor-tool/.1.5.1.15hiv04++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170730-09:36:24.742(2)? (STDERR) 						throw(ex);
W20170730-09:36:24.743(2)? (STDERR) 						^
W20170730-09:36:24.745(2)? (STDERR)
W20170730-09:36:24.747(2)? (STDERR) Error: Cannot find module './SimpleSchema'
W20170730-09:36:24.748(2)? (STDERR)     at makeMissingError (packages/modules-runtime.js:221:12)
W20170730-09:36:24.749(2)? (STDERR)     at require (packages/modules-runtime.js:231:19)
W20170730-09:36:24.754(2)? (STDERR)     at meteorInstall.node_modules.simpl-schema.dist.main.js (packages/modules.js:521:21)
W20170730-09:36:24.755(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170730-09:36:24.756(2)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170730-09:36:24.756(2)? (STDERR)     at meteorInstall.node_modules.meteor.aldeed:collection2-core.collection2.js (packages/aldeed:collection2-core/collection2.js:9:22)
W20170730-09:36:24.757(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170730-09:36:24.758(2)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170730-09:36:24.760(2)? (STDERR)     at /PATH_TO_MY_PROJECT/.meteor/local/build/programs/server/packages/aldeed_collection2-core.js:725:15
W20170730-09:36:24.761(2)? (STDERR)     at /PATH_TO_MY_PROJECT/.meteor/local/build/programs/server/packages/aldeed_collection2-core.js:736:3
```
At /PATH_TO_MY_PROJECT/.meteor/local/build/programs/server/packages/aldeed_collection2-core.js:725, I find:

`var exports = require("./node_modules/meteor/aldeed:collection2-core/collection2.js");`

But I realized that I don't have a `./node_modules/meteor` directory at all. Before trying to install these packages, the app was starting up just fine.

**Comment by aldeed** [comment] 2017-11-13 17:13
Closing this since it's old, but most likely this is a dependency issue. See my comment here: https://github.com/aldeed/meteor-collection2-core/issues/37#issuecomment-343950338

**Comment by crippledjosh** [comment] 2017-12-06 13:30
I am still getting this error with just simpl-schema installed. If i import it anywhere i get this error. If i install collection2-core i also get the error.

**Comment by aldeed** [comment] 2017-12-12 17:43
@crippledjosh If you are able to make a small app that reproduces the issue and post a repo link here, it will be much easier to find out what's going on.

**Closed** 2018-01-24 02:50 UTC
Labels: needs reproduction, potential bug
