### ISSUE TITLE
raix:eventemitter Constraint

### ISSUE THREAD

**Issue by flean** [aldeed/meteor-collection2-core#56] opened 2018-12-14 17:32 UTC
Can you remove the version constraint?
raix:eventemitter@0.1.3 <- aldeed:collection2-core 2.1.2

Thanks

**Comment by flean** [comment] 2018-12-14 17:34
the new version should be raix:eventemitter@1.0.0

**Comment by aldeed** [comment] 2019-02-05 01:37
Duplicate of https://github.com/aldeed/meteor-collection2/issues/386. Update to `aldeed:collection2@3.0.2`

**Closed as completed by aldeed** 2019-02-05 01:37 UTC
